<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Customer Statements</title><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/share.css') }}"></head><body>
@if(session('status'))<div class="toast success" role="status">{{ session('status') }}</div>@endif @if($errors->any())<div class="toast error" role="alert">{{ $errors->first() }}</div>@endif
<header class="app-header"><div><span class="eyebrow">FINANCE</span><h1>Customer statements</h1></div><div class="user-area"><span>{{ auth()->user()->name }}</span><form method="post" action="{{ route('logout') }}">@csrf<button>Sign out</button></form></div></header>
<main class="layout"><aside class="sidebar"><form method="get" action="{{ route('statements.index') }}" class="filters">
<label>Sales organization<select name="sales_org" onchange="this.form.sold_to_party.value='';this.form.submit()">@foreach($organizations as $org)<option value="{{ $org['sales_org'] }}" @selected(strcasecmp($salesOrg,$org['sales_org'])===0)>{{ strtoupper($org['sales_org']) }} · {{ number_format($org['customer_count']) }} customers</option>@endforeach</select></label>
<input type="hidden" name="sold_to_party" value="{{ $selected }}"><label>Search customers<div class="search-row"><input type="search" name="q" value="{{ $search }}" placeholder="Name, code, or address"><button>Search</button></div></label><div class="period-fields"><label>From<input type="date" name="from" value="{{ $from }}" required></label><label>To<input type="date" name="to" value="{{ $to }}" required></label></div>@if($selected)<button class="primary" type="submit">Update preview</button>@endif</form>
<div class="list-heading"><strong>Customers</strong><span>{{ $customers?->count() ?? 0 }} shown</span></div><nav class="customer-list" aria-label="Customers">
@forelse($customers ?? [] as $customer) @php($query=array_merge(request()->query(),['sales_org'=>$salesOrg,'sold_to_party'=>$customer->sold_to_party,'from'=>$from,'to'=>$to]))
<a class="customer {{ $selected===$customer->sold_to_party?'active':'' }}" href="{{ route('statements.index',$query) }}"><span class="avatar">{{ strtoupper(substr($customer->customer_name ?: $customer->sold_to_party,0,1)) }}</span><span><strong>{{ $customer->customer_name ?: 'Unnamed customer' }}</strong><small>{{ $customer->sold_to_party }}{{ $customer->state ? ' · '.$customer->state : '' }}</small></span><span class="chevron">›</span></a>
@empty<p class="empty-list">No customers match this search.</p>@endforelse</nav>@if($customers)<div class="pagination">{{ $customers->links() }}</div>@endif</aside>
<section class="preview-pane">@if($selected) @php($params=['sales_org'=>$salesOrg,'sold_to_party'=>$selected,'from'=>$from,'to'=>$to])
<div class="preview-toolbar"><div><span>Statement preview</span><strong>{{ $selected }}</strong></div><div class="preview-actions"><form action="{{ route('statements.share') }}" method="post" class="share-form">@csrf @foreach($params as $key=>$value)<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endforeach<input type="email" name="email" aria-label="Recipient email" placeholder="Recipient email address" required><button type="submit">Share PDF</button></form><a href="{{ route('statements.download',$params) }}">Download PDF</a><a href="{{ route('statements.preview',$params) }}" target="_blank">Open full page ↗</a></div></div><iframe title="Customer statement preview" src="{{ route('statements.preview',$params) }}"></iframe>
@else<div class="empty-state"><div class="document-icon">▤</div><h2>Select a customer</h2><p>Choose an account from the list to generate its statement preview.</p></div>@endif</section></main></body></html>
